feat: show full line and column position of misspellings on output
peckphp/peck pull request #28
Opened 2024-12-31 05:54 UTC by loki495

### What:

- [x] New Feature

### Description:

This PR calculates (naively) the column for each mispelling, and adds it to the output of each Issue:

- the <a> href and text  has the column now
- below the "ISSUE" line now we show the full line, and below that, there's an arrow pointing up at the character where the misspelling occurred

![PestCommitScreenshot](https://github.com/user-attachments/assets/ecea2a6c-ee17-4684-a43b-d5f2f30f8d0a)

2025-01-03 00:30 UTC, loki495 commented
Tweaked the output a bit, now it also uses termwind's <code> tag

![PeckPRScreenshot](https://github.com/user-attachments/assets/d0913e9b-357b-4a4f-98ab-61635f9e29db)

2025-01-04 19:23 UTC, nunomaduro requested changes
Can you check my review, but also fix the conflicts? Thank you, great work!

2025-01-04 19:23 UTC, nunomaduro commented on src/Console/Commands/DefaultCommand.php
> +        static $lastColumn = [];
Can you remove the `static`?

2025-01-04 19:23 UTC, nunomaduro commented on src/Console/Commands/DefaultCommand.php
> +            $align_spacer = str_repeat(' ', 6);
Can you use camelCase variables here?

2025-01-04 19:23 UTC, nunomaduro commented on src/Console/Commands/DefaultCommand.php
> +        if ($issue->line > 0) {
Can you create one separate method for each one of the `if` bodies?

2025-01-06 22:13 UTC, merged